// SPDX-License-Identifier: ISC

#include "types.hpp"

Object *fn_add(Object *);		    // '+'
Object *fn_apply(Object *);		    // 'apply'
Object *fn_as(Object *);		    // 'as'
Object *fn_car(Object *);		    // 'car'
Object *fn_cdr(Object *);		    // 'cdr'
Object *fn_concat(Object *);		    // 'concat'
Object *fn_cons(Object *);		    // 'cons'
Object *fn_divide(Object *);		    // '/'
Object *fn_equal(Object *);		    // '='
Object *fn_eval(Object *);		    // 'eval'
Object *fn_exponent(Object *);		    // '^'
Object *fn_fn(Object *);		    // 'fn'
Object *fn_greater_than(Object *);	    // '>'
Object *fn_greater_than_or_equal(Object *); // '>='
Object *fn_if(Object *);		    // 'if'
Object *fn_is(Object *);		    // 'is'
Object *fn_less_than(Object *);		    // '<'
Object *fn_less_than_or_equal(Object *);    // '<='
void fn_let(Object *, char *, void *);	    // 'let'
Object *fn_macro(Object *);		    // 'macro'
Object *fn_match(Object *);		    // 'match'
Object *fn_modulo(Object *);		    // '%'
Object *fn_multiply(Object *);		    // '*'
Object *fn_not(Object *);		    // 'not'
void fn_print(Object *);		    // 'print'
void fn_printf(char *, Object *);	    // 'printf'
Object *fn_quote(Object *);		    // 'quote', '\''
Object *fn_read(Object *);		    // 'read'
Object *fn_subtract(Object *);		    // '-'
Object *fn_typeof(Object *);		    // 'typeof'
