# SPDX-License-Identifier: ISC
---
name: Build

on:
  pull_request:
    paths:
      - .github/workflows/build.yaml
      - meson.build
      - include/**/*.h
      - include/**/meson.build
      - src/**/*.c
      - src/**/meson.build
  push:
    paths:
      - .github/workflows/build.yaml
      - meson.build
      - include/**/*.h
      - include/**/meson.build
      - src/**/*.c
      - src/**/meson.build
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang-12
          - gcc-10
        linker:
          - bfd
          - lld
        os:
          - name: ubuntu-latest
            deps: >-
              sudo apt update &&
              sudo apt-get install -y libgc-dev libreadline-dev meson

        # exclude:
        #   # https://gcc.gnu.org/bugzilla/show_bug.cgi?id=83243
        #   - compiler: gcc
        #     linker: lld

    name: ${{ matrix.compiler }}-${{ matrix.linker }} (${{ matrix.os.name }})
    runs-on: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: ${{ matrix.os.deps }}

      - name: Run Meson
        env:
          CC: "${{ matrix.compiler }}"
          CC_LD: "${{ matrix.linker }}"
        run: meson builddir

      - name: Build Ploy
        run: >-
          cd builddir &&
          ninja
