# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C Maudlin <jcmdln@gmail.com>
---
name: Build

on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - include/**/*.h
      - meson.build
      - src/**/*.c
      - src/**/meson.build
  push:
    paths:
      - .github/workflows/build.yml
      - include/**/*.h
      - meson.build
      - src/**/*.c
      - src/**/meson.build
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - clang-12
          - gcc-10
        linker:
          - bfd
          - lld
        os:
          - name: ubuntu-latest
            deps: >-
              sudo apt update &&
              sudo apt-get install -y libgc-dev libreadline-dev lld

    name: ${{ matrix.compiler }}-${{ matrix.linker }} (${{ matrix.os.name }})
    runs-on: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install system dependencies
        run: ${{ matrix.os.deps }}

      - name: Install Meson>=0.56
        run: pip install "meson>=0.56" ninja

      - name: Run Meson
        env:
          CC: "${{ matrix.compiler }}"
          CC_LD: "${{ matrix.linker }}"
        run: meson builddir

      - name: Build Ploy (Release)
        run: ninja -C builddir
