---
name: Build

on:
  pull_request:
    paths:
      - .github/**/*.yml
      - .github/**/*.yaml
      - meson.build
      - src/**/*.cpp
      - src/**/*.hpp
      - src/**/meson.build
  push:
    paths:
      - .github/**/*.yml
      - .github/**/*.yaml
      - meson.build
      - src/**/*.cpp
      - src/**/*.hpp
      - src/**/meson.build
  workflow_dispatch:

jobs:
  clang-12:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            ccache clang-12 libasan5 libgc-dev libreadline-dev libubsan1

      - name: Install meson and ninja via pip
        run: pip install "meson>=0.57" "ninja>=1.10"

      - name: Prepare build
        run: |
          CXX="ccache clang++" CXX_LD="lld" meson builddir -Dbuildtype=debug \
            -Dwerror=true -Doptimization=g -Db_sanitize=address,undefined

      - name: Build Ploy
        run: meson compile -C builddir

  gcc-10:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            ccache g++-10 libasan5 libgc-dev libreadline-dev libubsan1

      - name: Install meson and ninja via pip
        run: pip install "meson>=0.57" "ninja>=1.10"

      - name: Prepare build
        run: |
          CXX="ccache g++" meson builddir -Dbuildtype=debug -Dwerror=true \
            -Doptimization=g -Db_sanitize=address,undefined

      - name: Build Ploy
        run: meson compile -C builddir
