---
name: Build

on:
  pull_request:
    paths:
      - .github/**/*.yml
      - .github/**/*.yaml
      - meson.build
      - src/**/*.cpp
      - src/**/*.hpp
      - src/**/meson.build
  push:
    paths:
      - .github/**/*.yml
      - .github/**/*.yaml
      - meson.build
      - src/**/*.cpp
      - src/**/*.hpp
      - src/**/meson.build
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: clang-12
            deps: ccache clang-12 libasan5 libgc-dev libreadline-dev libubsan1
            cmd: clang++-12

          - name: gcc-10
            deps: ccache g++-10 libasan5 libgc-dev libreadline-dev libubsan1
            cmd: g++-10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.deps }}

      - name: Install meson and ninja via pip
        run: pip install "meson>=0.57" "ninja>=1.10"

      - name: Prepare build
        env:
          CXX: "ccache ${{matrix.cmd}}"
          CXX_LD: lld
        run: >-
          meson builddir -Dbuildtype=debug -Dwerror=true -Doptimization=g
          -Db_sanitize=address,undefined

      - name: Build Ploy
        run: meson compile -C builddir
