---
name: Build

on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - meson.build
      - src/**/*.c
      - src/**/*.h
      - src/**/meson.build
  push:
    paths:
      - .github/workflows/build.yml
      - meson.build
      - src/**/*.c
      - src/**/*.h
      - src/**/meson.build
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: clang-12
            deps: ccache clang-12 libasan5 libgc-dev libreadline-dev libubsan1
            cmd: clang-12
            compiler: clang-12
            linker: lld

          - name: gcc-10
            deps: ccache gcc-10 libasan5 libgc-dev libreadline-dev libubsan1
            compiler: gcc-10
            linker: bfd

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.deps }}

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install meson and ninja via pip
        run: pip install "meson>=0.57" "ninja>=1.10"

      - name: Prepare build
        env:
          CC: "ccache ${{ matrix.compiler }}"
          CC_LD: "${{ matrix.linker }}"
        run: >-
          meson builddir -Dbuildtype=debug -Dwerror=true -Doptimization=g -Db_sanitize=address,undefined

      - name: Build Ploy
        run: meson compile -C builddir
