---
name: Lint

on: [push, pull_request, workflow_dispatch]

jobs:
  clang-format:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install clang-format-12

      - name: Run clang-format
        run: |
          clang-format-12 --dry-run --style=file --Werror src/*

  clang-tidy:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install clang-tidy-12 libgc-dev libreadline-dev

      - name: Run clang-tidy
        run: |
          clang-tidy-12 --config-file=${{ github.workspace }}/.clang-tidy src/*
