# SPDX-License-Identifier: ISC
#
# Copyright (c) 2022 Johnathan C Maudlin <jcmdln@gmail.com>
---
name: Lint

on:
  pull_request:
    paths:
      - .clang-format
      - .clang-tidy
      - .github/workflows/lint.yaml
      - .prettierrc.yaml
      - include/**/*.c
      - include/**/meson.build
      - meson.build
      - src/**/*.c
      - src/**/meson.build
  push:
    paths:
      - .clang-format
      - .clang-tidy
      - .github/workflows/lint.yaml
      - .prettierrc.yaml
      - include/**/*.c
      - include/**/meson.build
      - meson.build
      - src/**/*.c
      - src/**/meson.build
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        linter:
          - name: clang-format
            cmd: clang-format --dry-run --Werror include/**/*.h src/**/*.c
          - name: clang-tidy
            cmd: clang-tidy -p ./builddir include/**/*.h src/**/*.c
        os:
          - name: ubuntu-latest
            deps: >-
              sudo apt update &&
              sudo apt-get install -y libasan5 libgc-dev libreadline-dev libubsan1

    name: ${{ matrix.linter.name }} (${{ matrix.os.name }})
    runs-on: ${{ matrix.os.name }}

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: ${{ matrix.os.deps }}

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Meson>=0.56
        run: pip install "meson>=0.56" ninja

      - name: Run Meson
        env:
          CC: clang-12
        run: >-
          meson builddir -Dbuildtype=debug -Doptimization=g -Dwerror=true \
            -Db_sanitize=address,undefined

      - name: Run ${{ matrix.linter.name }}
        run: ${{ matrix.linter.cmd }}

      - name: Build Ploy (Debug)
        run: >-
          cd builddir &&
          ninja
