---
name: Lint

on:
  pull_request:
    paths:
      - .github/workflows/lint.yml
      - meson.build
      - src/**/*.cpp
      - src/**/*.hpp
      - src/**/meson.build
  push:
    paths:
      - .github/workflows/lint.yml
      - meson.build
      - src/**/*.cpp
      - src/**/*.hpp
      - src/**/meson.build
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: clang-format-12
            deps: clang-format-12
            args: --dry-run --style=file --Werror
            targ: src/*.{c,h}pp

          - name: clang-tidy-12
            deps: clang-tidy-12 libgc-dev libreadline-dev
            args: --config-file=.clang-tidy
            targ: src/*.{c,h}pp

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.deps }}

      - name: Run ${{ matrix.name }}
        run: ${{ matrix.name }} ${{ matrix.args }} ${{ matrix.targ }}
