# SPDX-License-Identifier: ISC
#
# Copyright (c) 2023 Johnathan C Maudlin <jcmdln@gmail.com>
---
name: Test

on:
  pull_request:
    paths:
      - .clang-format
      - .clang-tidy
      - .clangd
      - .github/workflows/test.yml
      - meson.build
      - include/**/*.h
      - src/**/*.c
      - src/**/meson.build
  push:
    paths:
      - .clang-format
      - .clang-tidy
      - .clangd
      - .github/workflows/test.yml
      - meson.build
      - include/**/*.h
      - src/**/*.c
      - src/**/meson.build
  workflow_dispatch:

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-{recommends,suggests} \
            clang{,-{format,tidy}} git lld meson ninja-build \
            libgc-dev libreadline-dev libasan5 libubsan1

      - name: Build Ploy
        env: { CC: clang, CC_LD: lld, NINJA: ninja }
        run: |
          meson setup builddir -Db_sanitize=address,undefined -Dbuildtype=debugoptimized
          ninja -C builddir

      - name: Test Ploy
        run: ninja -C builddir test

      - name: clang-format
        run: ninja -C builddir clang-format

      # TODO(jcmdln): Only in actions, clang-tidy warns about suppressed warnings
      - name: clang-tidy
        run: ninja -C builddir clang-tidy
